// levels.js — Definisi level dan tantangan
// Dimuat setelah data.js
//
// Field `short`  : label pendek untuk penunjuk langkah (stepper)
// Field `bonus`  : { type, target, score, label } — dievaluasi di app.js
//                  type: 'totalItems' | 'uniqueFoods' | 'newFoods' | 'nutriScore'

const LEVELS = [
  {
    id: 1,
    title: 'Level 1',
    name: 'Sarapan Keluarga Rani',
    icon: '🍳',
    concept: 'Mengenal Isi Piringku',
    color: '#16A34A',
    storyIcon: '👧',
    story: 'Rani mau berangkat ke sekolah kejar paket. Dia sering lemas karena sarapannya tidak lengkap. Bantu Ibu Rani menyiapkan sarapan bergizi!',
    nutritionTarget: 'anak',
    challenges: [
      {
        id: '1A',
        title: 'Sarapan Hari Kerja',
        short: 'Hari Kerja',
        mission: 'Pilih sarapan untuk Rani. Pastikan ada <strong>makanan pokok, lauk, sayuran, dan buah</strong> di piringnya!',
        context: '☀️ Senin pagi — Rani harus berangkat pukul 06.30',
        availableFoods: ['nasi_putih','roti_tawar','mie_telur','tempe','tahu_goreng','telur_rebus','bayam','kangkung','wortel','pisang_ambon','pepaya','semangka'],
        maxPerZone: 2, budget: null, requireAllZones: true,
        hint: 'Isi keempat bagian piring dulu, satu per satu: makanan pokok (nasi atau roti), lauk (tempe, tahu, atau telur), sayuran, lalu buah.',
        feedbackGood: 'Wah, Rani semangat berangkat ke sekolah! Energinya cukup untuk belajar seharian! 💪',
        feedbackBad: 'Rani masih agak lemas di kelas. Coba lengkapi keempat bagian piringnya, ya!',
      },
      {
        id: '1B',
        title: 'Sarapan Hari Libur',
        short: 'Hari Libur',
        mission: 'Hari libur — ada waktu lebih! Buat sarapan yang <strong>lebih lengkap dan beragam</strong> untuk Rani dan Ibu.',
        context: '🌤️ Sabtu pagi — santai, boleh masak lebih lama',
        availableFoods: ['nasi_putih','nasi_merah','roti_gandum','roti_tawar','tempe','tahu_goreng','telur_rebus','telur_ceplok','ikan_kembung','bayam','kangkung','wortel','brokoli','tomat','pisang_ambon','pepaya','jeruk_manis','mangga'],
        maxPerZone: 3, budget: null, requireAllZones: true,
        bonus: { type: 'totalItems', target: 7, score: 15, label: 'Sajikan 7 makanan atau lebih' },
        hint: 'Karena tidak buru-buru, tambahkan porsi kedua di beberapa bagian. Tujuh makanan atau lebih akan memberi poin bonus.',
        feedbackGood: 'Menu sarapan hari libur yang luar biasa! Rani dan Ibu siap menyambut hari yang menyenangkan! 🌟',
        feedbackBad: 'Sarapannya masih bisa lebih lengkap. Coba tambahkan bagian yang masih kosong.',
      },
      {
        id: '1C',
        title: 'Sarapan Super Cepat!',
        short: 'Super Cepat',
        mission: '⏰ Rani kesiangan! Pilih <strong>maksimal 4 makanan</strong> saja — tapi harus tetap ada 4 komponen Isi Piringku!',
        context: '🚨 Sudah pukul 06.15! Bus sebentar lagi datang!',
        availableFoods: ['roti_gandum','roti_tawar','telur_rebus','tahu_goreng','tempe','wortel','tomat','pisang_ambon','pepaya','jambu_biji'],
        maxPerZone: 1, maxTotalItems: 4, budget: null, requireAllZones: true,
        hint: 'Empat makanan untuk empat bagian, jadi tepat satu makanan di tiap bagian. Pilih yang paling padat gizinya, misalnya roti gandum dan telur.',
        feedbackGood: 'Rani berhasil sarapan lengkap dalam waktu singkat! Hebat sekali! 🏃‍♀️',
        feedbackBad: 'Waktunya hampir habis! Pastikan setiap bagian piring terisi meski hanya 1 makanan.',
      },
    ],
  },

  {
    id: 2,
    title: 'Level 2',
    name: 'Belanja di Pasar Pagi',
    icon: '🛒',
    concept: 'Nilai Gizi vs Harga',
    color: '#EA580C',
    storyIcon: '🧑‍🌾',
    story: 'Pak Budi pergi ke pasar pagi dengan uang terbatas. Bantu belanja bahan makanan bergizi tanpa melebihi anggaran!',
    nutritionTarget: 'anak',
    challenges: [
      {
        id: '2A',
        title: 'Anggaran Rp 30.000',
        short: 'Rp 30.000',
        mission: 'Susun menu makan siang dengan anggaran <strong>Rp 30.000</strong>. Cari kombinasi paling bergizi!',
        context: '🛒 Harga mengacu rata-rata pasar tradisional Indonesia',
        availableFoods: ['nasi_putih','singkong','ubi_jalar','tempe','tahu_goreng','telur_rebus','ikan_kembung','ikan_asin','bayam','kangkung','daun_singkong','kacang_panjang','tomat','pisang_ambon','pepaya','semangka','jambu_biji'],
        maxPerZone: 3, budget: 30000, requireAllZones: true,
        hint: 'Perhatikan harga di tiap kartu bahan. Singkong dan ubi jalar lebih murah daripada nasi, tapi kalorinya mirip.',
        feedbackGood: 'Belanja cerdas! Anggaran efisien dan gizi tetap terpenuhi! 🎯',
        feedbackBad: 'Anggarannya terlampaui. Coba ganti beberapa bahan dengan yang lebih terjangkau.',
      },
      {
        id: '2B',
        title: 'Anggaran Rp 20.000',
        short: 'Rp 20.000',
        mission: 'Anggaran lebih ketat: <strong>Rp 20.000</strong>. Temukan kombinasi paling bergizi!',
        context: '💡 Petunjuk: Tempe dan tahu adalah sumber protein termurah!',
        availableFoods: ['nasi_putih','singkong','ubi_jalar','tempe','tahu_goreng','telur_rebus','ikan_asin','bayam','kangkung','daun_singkong','kacang_panjang','tomat','pisang_ambon','pepaya','jambu_biji'],
        maxPerZone: 2, budget: 20000, requireAllZones: true,
        hint: 'Tempe Rp 2.000 memberi 19 g protein — lebih murah per gram protein daripada ikan kembung. Daun singkong hanya Rp 1.000 dan kaya serat.',
        feedbackGood: 'Luar biasa! Kamu menemukan rahasianya: gizi seimbang tidak harus mahal! 💚',
        feedbackBad: 'Anggaran terlampaui atau piring belum lengkap. Coba pilih bahan yang lebih hemat.',
      },
      {
        id: '2C',
        title: 'Anggaran Rp 15.000',
        short: 'Rp 15.000',
        mission: 'Tantangan terberat! Hanya <strong>Rp 15.000</strong>. Buktikan gizi seimbang bisa dengan anggaran minimum!',
        context: '🏆 Ini tantangan tersulit — tapi bisa dilakukan dengan kreativitas!',
        availableFoods: ['singkong','ubi_jalar','nasi_putih','tempe','tahu_goreng','ikan_asin','bayam','daun_singkong','kangkung','tomat','pisang_ambon','pepaya','jambu_biji'],
        maxPerZone: 2, budget: 15000, requireAllZones: true,
        hint: 'Coba mulai dari bahan termurah di tiap bagian: singkong (Rp 1.500), tempe (Rp 2.000), daun singkong (Rp 1.000), pisang (Rp 2.000). Sisa anggaran bisa untuk menambah porsi.',
        feedbackGood: 'Luar biasa! Kamu membuktikan: dengan kreativitas, anggaran terbatas pun bisa bergizi! 🌟',
        feedbackBad: 'Sudah dekat! Coba pilih bahan paling murah di setiap kategori.',
      },
    ],
  },

  {
    id: 3,
    title: 'Level 3',
    name: 'Menu 7 Hari',
    icon: '📅',
    concept: 'Keanekaragaman Pangan',
    color: '#7C3AED',
    storyIcon: '👨‍👩‍👧',
    story: 'Ibu Ani mau merencanakan menu makan siang 7 hari untuk keluarganya. Bantu buat menu yang bervariasi setiap harinya!',
    nutritionTarget: 'anak',
    challenges: [
      {
        id: '3A',
        title: 'Hari 1–3: Mulai Merencanakan',
        short: 'Hari 1–3',
        mission: 'Susun menu makan siang untuk <strong>3 hari pertama</strong>. Semakin beragam bahannya, semakin baik!',
        context: '📋 Bahan yang kamu pakai di sini akan dicatat untuk tantangan berikutnya',
        availableFoods: ['nasi_putih','nasi_merah','jagung_rebus','tempe','tahu_goreng','telur_rebus','telur_ceplok','ayam_goreng','ikan_kembung','ikan_asin','bayam','kangkung','wortel','kacang_panjang','tomat','pisang_ambon','pepaya','jeruk_manis','semangka'],
        maxPerZone: 2, budget: null, requireAllZones: true,
        days: 3,
        bonus: { type: 'uniqueFoods', target: 5, score: 15, label: 'Pakai 5 jenis bahan berbeda' },
        hint: 'Variasi itu kunci. Daripada dua porsi nasi, coba satu nasi dan satu jagung rebus — gizinya jadi lebih beragam.',
        feedbackGood: 'Menu 3 hari pertama sudah bervariasi! Keluarga pasti senang! 🎉',
        feedbackBad: 'Coba isi keempat bagian piring untuk menu hari ini.',
      },
      {
        id: '3B',
        title: 'Hari 4: Kejutan!',
        short: 'Hari 4',
        mission: '😱 <strong>Pasar tutup!</strong> Hanya ada bahan sisa di kulkas. Berkreasi dengan bahan yang ada!',
        context: '🥶 Sisa kulkas hari ke-4 — bahan terbatas, kreativitas tanpa batas!',
        availableFoods: ['nasi_putih','ubi_jalar','tempe','tahu_goreng','telur_rebus','daun_singkong','kangkung','tomat','pisang_ambon'],
        maxPerZone: 2, budget: null, requireAllZones: true,
        days: 1,
        isSpecial: true,
        hint: 'Bahannya sedikit, tapi keempat bagian tetap bisa terisi. Ubi jalar bisa menggantikan nasi, dan daun singkong kaya serat.',
        feedbackGood: 'Hebat! Dengan bahan terbatas pun menu tetap bergizi! Ini namanya kreatif! ✨',
        feedbackBad: 'Bahannya memang terbatas, tapi coba tetap isi keempat bagian piringnya.',
      },
      {
        id: '3C',
        title: 'Hari 5–7: Selesaikan Menu!',
        short: 'Hari 5–7',
        mission: 'Selesaikan <strong>3 hari terakhir</strong>. Pakai bahan <strong>baru</strong> yang belum kamu gunakan di hari 1–4!',
        context: '🌟 Bahan yang sudah dipakai ditandai. Cari yang masih segar!',
        availableFoods: ['nasi_putih','nasi_merah','roti_gandum','singkong','tempe','tahu_goreng','ikan_kembung','ikan_lele','udang_rebus','daging_sapi','telur_ceplok','bayam','brokoli','wortel','terong','kacang_panjang','mangga','jeruk_manis','apel','alpukat','semangka','nanas'],
        maxPerZone: 2, budget: null, requireAllZones: true,
        days: 3,
        bonus: { type: 'newFoods', target: 4, score: 15, label: 'Pakai 4 bahan yang belum dipakai minggu ini' },
        hint: 'Bahan bertanda "sudah dipakai" pernah kamu gunakan di hari 1–4. Pilih yang tidak bertanda untuk mendapat poin bonus.',
        feedbackGood: 'Menu 7 hari selesai! Keluarga mendapat gizi beragam sepanjang minggu! 🏆',
        feedbackBad: 'Ayo lengkapi piringnya — variasi pangan itu penting untuk kesehatan.',
      },
    ],
  },

  {
    id: 4,
    title: 'Level 4',
    name: 'Gizi untuk Kondisi Khusus',
    icon: '💊',
    concept: 'Kebutuhan Gizi Berbeda-beda',
    color: '#0891B2',
    storyIcon: '👨‍⚕️',
    story: 'Setiap orang punya kebutuhan gizi yang berbeda! Bantu susun menu yang tepat untuk anggota keluarga dengan kondisi khusus.',
    challenges: [
      {
        id: '4A',
        title: 'Menu untuk Ibu Hamil',
        short: 'Ibu Hamil',
        mission: 'Ibu Dewi sedang hamil 7 bulan. Susun menu yang <strong>tinggi zat besi, protein, dan beragam sayuran</strong>!',
        context: '👶 Ibu hamil butuh asupan gizi ekstra untuk tumbuh kembang janin',
        character: 'Ibu Dewi (hamil 7 bulan)',
        storyIcon: '🤰',
        nutritionTarget: 'ibuHamil',
        availableFoods: ['nasi_merah','roti_gandum','tempe','tahu_goreng','telur_rebus','ikan_kembung','hati_ayam','daging_sapi','bayam','kangkung','brokoli','kacang_panjang','tomat','pepaya','jeruk_manis','mangga','alpukat'],
        maxPerZone: 3, budget: null, requireAllZones: true,
        hint: 'Ibu hamil sangat butuh zat besi (bayam, hati ayam) dan protein tinggi (ikan, telur, tempe). Targetnya lebih besar, jadi tambahkan porsi.',
        feedbackGood: 'Menu sempurna untuk Ibu Dewi! Bayi dalam kandungan pasti tumbuh sehat! 👶💚',
        feedbackBad: 'Ibu hamil butuh gizi ekstra. Pastikan ada protein tinggi, sayuran hijau, dan buah kaya vitamin.',
      },
      {
        id: '4B',
        title: 'Menu untuk Lansia',
        short: 'Lansia',
        mission: 'Kakek Soni (65 tahun) butuh menu <strong>tinggi serat, mudah dicerna</strong>, dan tidak terlalu asin.',
        context: '👴 Lansia perlu perhatian khusus: pencernaan, tulang, dan tekanan darah',
        character: 'Kakek Soni (65 tahun)',
        storyIcon: '👴',
        nutritionTarget: 'lansia',
        availableFoods: ['nasi_putih','ubi_jalar','bubur_ayam','tahu_goreng','tempe','ikan_kembung','telur_rebus','udang_rebus','bayam','wortel','brokoli','tomat','timun','pepaya','pisang_ambon','semangka','alpukat'],
        maxPerZone: 3, budget: null, requireAllZones: true,
        hint: 'Lansia butuh serat tinggi (sayuran, buah) untuk pencernaan dan kalsium (tahu, ikan) untuk tulang. Kalorinya justru lebih rendah dari orang dewasa.',
        feedbackGood: 'Menu yang cocok untuk Kakek Soni! Beliau akan lebih sehat dan aktif! 💪👴',
        feedbackBad: 'Kakek Soni butuh makanan yang mudah dicerna dan kaya serat. Coba tambah sayur dan buah.',
      },
      {
        id: '4C',
        title: 'Menu untuk Remaja Aktif',
        short: 'Remaja Aktif',
        mission: 'Budi (15 tahun) aktif berolahraga tiap hari. Butuh <strong>kalori dan protein tinggi</strong> untuk energi & tumbuh kembang!',
        context: '⚽ Remaja aktif membutuhkan energi jauh lebih banyak dari biasanya',
        character: 'Budi (15 tahun, atlet voli)',
        storyIcon: '🏐',
        nutritionTarget: 'remaja',
        availableFoods: ['nasi_putih','nasi_merah','jagung_rebus','roti_gandum','ketupat','ayam_goreng','ikan_kembung','telur_rebus','telur_ceplok','daging_sapi','tempe','tahu_goreng','kangkung','bayam','wortel','brokoli','pisang_ambon','mangga','alpukat','semangka','nanas'],
        maxPerZone: 3, budget: null, requireAllZones: true,
        hint: 'Remaja aktif butuh karbohidrat banyak untuk energi, protein untuk otot, dan buah untuk pemulihan. Jangan ragu menambah porsi makanan pokok.',
        feedbackGood: 'Menu Budi sempurna! Dia siap bermain voli dengan penuh semangat! 🏐🌟',
        feedbackBad: 'Remaja aktif butuh lebih banyak porsi. Perbesar porsi makanan pokok dan lauk proteinnya.',
      },
    ],
  },

  {
    id: 5,
    title: 'Level 5',
    name: 'Ahli Gizi Keluargaku',
    icon: '🏆',
    concept: 'Perencanaan Menu Bebas',
    color: '#DB2777',
    storyIcon: '👨‍⚕️',
    story: 'Sekarang giliranmu jadi ahli gizi! Gunakan semua yang sudah kamu pelajari untuk menyusun menu terbaik!',
    nutritionTarget: 'default',
    challenges: [
      {
        id: '5A',
        title: 'Menu Bebas Terbaik',
        short: 'Menu Bebas',
        mission: 'Rancang menu seimbang terbaik dari semua bahan. Raih <strong>skor gizi minimal 75</strong> — tembus <strong>85</strong> untuk poin bonus!',
        context: '🎯 Tidak ada batasan bahan — pilih kombinasi terbaikmu',
        availableFoods: '__ALL__',
        maxPerZone: 4, budget: null, requireAllZones: true, minNutriScore: 75,
        bonus: { type: 'nutriScore', target: 85, score: 15, label: 'Tembus skor gizi 85' },
        hint: 'Perhatikan panel gizi: kejar semua batang mendekati 100%. Kalau lemak masih rendah, alpukat atau telur bisa membantu tanpa menambah banyak kalori.',
        feedbackGood: 'Luar biasa! Kamu sudah layak menjadi Ahli Gizi Keluarga! 🏆',
        feedbackBad: 'Skor gizinya belum mencapai target. Perhatikan keseimbangan kelima zat gizi.',
      },
      {
        id: '5B',
        title: 'Menu Hemat & Sehat',
        short: 'Hemat & Sehat',
        mission: 'Dengan <strong>anggaran Rp 25.000</strong>, susun menu paling bergizi. Buktikan sehat itu tidak mahal!',
        context: '💰 Tantangan akhir: efisiensi + gizi seimbang dalam satu piring',
        availableFoods: '__ALL__',
        maxPerZone: 3, budget: 25000, requireAllZones: true, minNutriScore: 70,
        hint: 'Gabungkan pelajaran level 2 dan level 5: bahan murah padat gizi (tempe, daun singkong, singkong, pisang), lalu sisakan anggaran untuk menambah porsi.',
        feedbackGood: 'Sempurna! Kamu membuktikan gizi seimbang bisa diraih dengan anggaran terbatas! 🌟',
        feedbackBad: 'Coba atur ulang pilihan makanan — anggaran dan gizi harus seimbang.',
      },
    ],
  },
];
